"""Shared path, serialization and implementation-evidence contracts."""

from __future__ import annotations

import hashlib
import importlib.metadata
import json
import platform
import re
import stat
from pathlib import Path, PurePosixPath, PureWindowsPath
import zipfile


class AssuranceError(ValueError):
    """An allowlisted request error; the message must contain only a code."""


def canonical_bytes(value: object) -> bytes:
    return (json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n").encode()


def digest(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def read_json(path: Path) -> dict:
    reject_symlinks(path)
    if not path.is_file():
        raise AssuranceError("REGULAR_FILE_REQUIRED")
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (UnicodeError, json.JSONDecodeError) as exc:
        raise AssuranceError("INVALID_JSON") from exc
    if type(value) is not dict:
        raise AssuranceError("JSON_OBJECT_REQUIRED")
    return value


def write_json(path: Path, value: object) -> None:
    path.write_bytes(canonical_bytes(value))


def reject_symlinks(path: Path) -> None:
    absolute = path.absolute()
    if ".." in path.parts:
        raise AssuranceError("PATH_TRAVERSAL")
    if any(p.is_symlink() for p in (absolute, *absolute.parents)):
        raise AssuranceError("SYMLINK_REFUSED")


def relative_path(value: object) -> str:
    if not isinstance(value, str) or not value or "\\" in value or "\x00" in value:
        raise AssuranceError("RELATIVE_PATH_REQUIRED")
    path = PurePosixPath(value)
    if path.is_absolute() or PureWindowsPath(value).drive or any(p in {"", ".", ".."} or ":" in p for p in value.split("/")):
        raise AssuranceError("PATH_TRAVERSAL")
    return value


def safe_child(root: Path, value: object) -> Path:
    path = root / relative_path(value)
    reject_symlinks(path)
    if not path.resolve().is_relative_to(root.resolve()):
        raise AssuranceError("PATH_TRAVERSAL")
    return path


def new_output(path: Path) -> None:
    reject_symlinks(path)
    if path.exists():
        raise AssuranceError("OUTPUT_EXISTS")
    path.mkdir(parents=True)


def files_under(root: Path) -> list[Path]:
    reject_symlinks(root)
    if not root.is_dir():
        raise AssuranceError("DIRECTORY_REQUIRED")
    result: list[Path] = []
    # Inspect before descending: Path.rglob can hide symlink-directory inputs.
    def visit(directory: Path) -> None:
        for path in sorted(directory.iterdir()):
            mode = path.lstat().st_mode
            if stat.S_ISLNK(mode):
                raise AssuranceError("SYMLINK_REFUSED")
            if stat.S_ISDIR(mode):
                visit(path)
            elif stat.S_ISREG(mode):
                result.append(path)
            else:
                raise AssuranceError("SPECIAL_FILE_REFUSED")
    visit(root)
    return result


def tree_hashes(root: Path) -> dict[str, str]:
    return {p.relative_to(root).as_posix(): file_digest(p) for p in files_under(root)}


def file_digest(path: Path) -> str:
    reject_symlinks(path)
    if not path.is_file():
        raise AssuranceError("REGULAR_FILE_REQUIRED")
    hasher = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            hasher.update(block)
    return hasher.hexdigest()


def valid_law_id(value: object) -> bool:
    # A serialization safety constraint, not proof of official registration.
    # Do not publish arbitrary path/text payloads supplied as an XML attribute.
    return isinstance(value, str) and re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_.-]{0,127}", value) is not None


def package_code_hashes() -> dict[str, str]:
    import jlegal_okf
    root = Path(jlegal_okf.__file__).parent
    return {p.relative_to(root).as_posix(): file_digest(p)
            for p in files_under(root) if p.suffix == ".py"}


def implementation_identity() -> dict:
    """Fingerprint actual imported code and runtime, ignoring generated bytecode."""
    from jlegal_okf import __version__
    return {
        "package_version": __version__,
        "package_tree_sha256": digest(canonical_bytes(package_code_hashes())),
        "python_version": platform.python_version(),
        "dependencies": {name: importlib.metadata.version(name)
                         for name in ("defusedxml", "httpx", "PyYAML")},
    }


def verify_implementation_lock(path: Path) -> dict:
    lock = read_json(path)
    required = {"schema", "artifact_kind", "package_version", "package_tree_sha256", "source_revision"}
    if not required <= lock.keys() or lock["schema"] != "jlegal-implementation-lock/v1":
        raise AssuranceError("IMPLEMENTATION_LOCK_SHAPE")
    if lock["artifact_kind"] not in {"candidate-source", "installed-wheel"}:
        raise AssuranceError("IMPLEMENTATION_LOCK_KIND")
    revision = lock["source_revision"]
    if revision is not None and (not isinstance(revision, str) or not re.fullmatch(r"[0-9a-f]{40}", revision)):
        raise AssuranceError("IMPLEMENTATION_LOCK_REVISION")
    actual = implementation_identity()
    if any(lock[key] != actual[key] for key in ("package_version", "package_tree_sha256")):
        raise AssuranceError("IMPLEMENTATION_LOCK_MISMATCH")
    for key in ("python_version", "dependencies"):
        if key in lock and lock[key] != actual[key]:
            raise AssuranceError("IMPLEMENTATION_RUNTIME_MISMATCH")
    wheel_sha = None
    if lock["artifact_kind"] == "installed-wheel":
        wheel = safe_child(path.parent, lock.get("wheel_file"))
        wheel_sha = file_digest(wheel)
        if wheel_sha != lock.get("wheel_sha256"):
            raise AssuranceError("IMPLEMENTATION_WHEEL_HASH")
        with zipfile.ZipFile(wheel) as archive:
            code = {}
            for name in archive.namelist():
                if name.startswith("jlegal_okf/") and name.endswith(".py"):
                    relative_path(name)
                    relative = name[len("jlegal_okf/"):]
                    if relative in code:
                        raise AssuranceError("IMPLEMENTATION_WHEEL_DUPLICATE")
                    code[relative] = digest(archive.read(name))
            if code != package_code_hashes():
                raise AssuranceError("IMPLEMENTATION_WHEEL_CODE")
        if importlib.metadata.version("jlegal-okf") != actual["package_version"]:
            raise AssuranceError("IMPLEMENTATION_DISTRIBUTION_VERSION")
        distribution = importlib.metadata.distribution("jlegal-okf")
        import jlegal_okf
        if Path(distribution.locate_file("jlegal_okf/__init__.py")).resolve() != Path(jlegal_okf.__file__).resolve():
            raise AssuranceError("IMPLEMENTATION_DISTRIBUTION_ORIGIN")
    return {**actual, "artifact_kind": lock["artifact_kind"],
            "lock_sha256": file_digest(path), "wheel_sha256": wheel_sha,
            "claimed_source_revision": revision, "revision_verification": "unverified",
            "package_code_verification": "verified"}
